spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-devit-chat.copkmnpqtze8.ap-northeast-2.rds.amazonaws.com:3306/devit_chat?characterEncoding=utf8
    username: daehee
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  profiles:
    include: API-KEY

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
