spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-devit-chat.copkmnpqtze8.ap-northeast-2.rds.amazonaws.com:3306/devit_chat?characterEncoding=utf8
    username: daehee
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: chat-service

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.180.93.206:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true